config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  get 'combos/booking', to: "combos#booking"
  resource :home, only: %i[ index ]
  resources :dashboard, only: %i[ index ]
  resources :articles, only: %i[ index show new create edit update ]
  resources :combos, only: %i[ index show new create edit update booking ]
  resource :contact, only: %i[ show edit update ]
  resource :association, only: %i[ show edit update ]

  # manually added links because the routing system is shit
  get 'association/commissions', to: "associations#commissions"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Anyone can see the index of news and individual articles
    can %i[ index show ], Article

    # Anyone can see the index of bands and individual band profiles
    can %i[ index show ], Combo
    can %i[ show ], Contact

    # Anyone can see the association information
    can %i[ show commissions ], Association

    if user.has_role? :admin
      # An administrator must be able to do anything in the system
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    dragonfly_accessor :cover

    validates_property :mime_type, of: :cover, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/association.rb
class Association < ApplicationRecord
	dragonfly_accessor :banner

	validates_property :mime_type, of: :banner, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/combo.rb
class Combo < ActiveRecord::Base
    dragonfly_accessor :cover
    dragonfly_accessor :tile

    validates_property :mime_type, of: :cover, in: %w(image/jpeg image/jpg image/png image/gif)
    validates_property :mime_type, of: :tile, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/commission.rb
class Commission < ActiveRecord::Base
	
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def index
    @article = Article.all
    @association = Association.first
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'Het artikel is aangemaakt.'
      redirect_to articles_path
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'new'
    end
  end

  def edit; end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      flash[:success] = 'Het artikel is aangepast.'
      redirect_to article_path(@article)
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'edit'
    end
  end

  protected

  def article_params
    params.require(:article).permit(:title, :content, :cover)
  end
end

app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  load_and_authorize_resource

  def show
  	@association = Association.first;
  end

  def edit
  	@association = Association.first;
  end

  def update
  	@association = Association.first;

  	if @association.update_attributes(association_params)
  		flash[:succes] = 'De vereniging informatie is aangepast.'
  		redirect_to action: "show"
  	else
  		flash[:danger] = 'Er is iets fout gegaan gedurende het opslaan.'
  		render 'edit'
  	end
  end

  def commissions
    @commissions = Commission.all;
    render 'commissions'
  end

  def association_params
    params.require(:association).permit(:content)
  end
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  load_and_authorize_resource

  def index
    @combo = Combo.all
  end

  def show; end

  def new
    @combo = Combo.new
  end

  def create
    @combo = Combo.new(combo_params)

    if @combo.save
      flash[:success] = 'De combo is aangemaakt.'
      redirect_to combos_path
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'new'
    end
  end

  def edit; end

  def update
    @combo = Combo.find(params[:id])

    if @combo.update_attributes(combo_params)
      flash[:success] = 'Het combo is aangepast.'
      redirect_to combo_path(@combo)
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'edit'
    end
  end

  def booking
    @combo = Combo.first
    @contact = Contact.first
  end

  protected

  def combo_params
    params.require(:combo).permit(:name, :description, :cover, :music_uid, :facebook_uid, :twitter_uid, :short_text)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  load_and_authorize_resource

  def show
  	@contact = Contact.first;
  end

  def edit
  	@contact = Contact.first;
  end

  def update
  	@contact = Contact.first;

  	if @contact.update_attributes(contact_params)
  		flash[:succes] = 'De contactinformatie is aangepast.'
  		redirect_to action: "show"
  	else
  		flash[:danger] = 'Er is iets fout gegaan gedurende het opslaan.'
  		render 'edit'
  	end
  end

  def contact_params
    params.require(:contact).permit(:content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
     { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
   end

   def flash_messages(opts = {})
     flash.each do |msg_type, message|
       concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
               concat message
             end)
     end
     nil
   end
end

app/helpers/association_helper.rb
module AssociationHelper
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<% content_for :articlemenu do %>
  <% if can? :new, :article %>
    <li class="nav-item"><%= link_to 'Nieuw bericht', new_article_path, class: 'sub-nav-link' %></li>
    <li class="nav-item"><%= link_to 'Bericht aanpassen', edit_article_path(@article), class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Terug naar overzicht', articles_path, class: 'sub-nav-link' %></li>
<% end %>
<div class = "paddedcontainer-large">
  <h1>Artikel Aanpassen</h1>
  <%= bootstrap_form_for @article do |a| %>
    <%= a.text_field :title %>
    <%= a.text_area :content %>
    <%= a.file_field :cover %>
    <%= a.submit 'Artikel aanpassen', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    ClassicEditor
        .create( document.querySelector( '#article_content' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

app/views/articles/index.html.erb
<% render 'articles/shared/contextlinks' %>
<% if Article.none? %>
  <h1>There are no articles in the website database.</h1>
<% else %>
  <div class = "paddedcontainer-medium">
    <div class="row">
      <% @article.reverse_each do |carticle| %>
        <div class="col-sm-12 col-md-6">
          <div class="thumbnail">
            <%= image_tag carticle.cover.url %>
            <div class="caption">
              <h3><%= carticle.title %></h3>
              <p><%= carticle.content.truncate(100).html_safe %></p>
              <p><%= link_to 'Lees meer', article_path(carticle.id), class: 'btn btn-primary' %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<% render 'articles/shared/contextlinks' %>
<div class = "paddedcontainer-large">
  <h1>Nieuw Artikel</h1>
  <%= bootstrap_form_for @article do |a| %>
    <%= a.text_field :title %>
    <%= a.text_area :content %>
    <%= a.file_field :cover %>
    <%= a.submit 'Nieuw artikel aanmaken', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    ClassicEditor
        .create( document.querySelector( '#article_content' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

app/views/articles/shared/_contextlinks.html.erb
<% content_for :articlemenu do %>
  <% if can? :new, :article %>
    <li class="nav-item"><%= link_to 'Nieuw bericht', new_article_path, class: 'sub-nav-link' %></li>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<% content_for :articlemenu do %>
  <% if can? :new, :article %>
    <li class="nav-item"><%= link_to 'Nieuw bericht', new_article_path, class: 'sub-nav-link' %></li>
    <li class="nav-item"><%= link_to 'Bericht aanpassen', edit_article_path(@article), class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Terug naar overzicht', articles_path, class: 'sub-nav-link' %></li>
<% end %>
<div class="thumbnail">
  <%= image_tag @article.cover.url %>
</div>
<div class = "paddedcontainer-medium">
  <h2><%= @article.title %></h2>
    <div class ="containernews">
      <p><%= @article.content.html_safe %></p>
  </div>
</div>

app/views/associations/commissions.html.erb
<% content_for :associationmenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Aanpassen', edit_association_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Commissies', association_commissions_path, class: 'sub-nav-link' %></li>
<% end %>

<div class = "paddedcontainer-large">
	<h1>Commissies</h1>

	<% @commissions.each do |commission| %>
		<h3><%= commission.name %></h3>
		<p><%= commission.description %></p>
	<% end %>
</div>

app/views/associations/edit.html.erb
<% content_for :associationmenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Aanpassen', edit_association_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Commissies', association_commissions_path, class: 'sub-nav-link' %></li>
<% end %>

<div class = "paddedcontainer-large">
  <h1>Verenging informatie aanpassen</h1>
  <%= bootstrap_form_for @association do |a| %>
  	<%= a.text_area :content %>
    <%= a.file_field :banner %>
    <%= a.submit 'Verenging informatie aanpassen', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    ClassicEditor
        .create( document.querySelector( '#association_content' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

app/views/associations/show.html.erb
<% content_for :associationmenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Aanpassen', edit_association_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Commissies', association_commissions_path, class: 'sub-nav-link' %></li>
<% end %>

<div class = "paddedcontainer-large">
	<h1>Vereniging</h1>

	<p><%= @association.content.html_safe %></p>
</div>

app/views/combos/booking.html.erb
<% content_for :combomenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Nieuwe combo', new_combo_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Boeken', combos_booking_path, class: 'sub-nav-link' %></li>
<% end %>

<div class = "paddedcontainer-large">
	<h1>Boeken</h1>
	<p><%= @contact.bookingcontent.html_safe %></p>
</div>

app/views/combos/edit.html.erb
<% content_for :combomenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Nieuwe combo', new_combo_path, class: 'sub-nav-link' %></li>
  <% end %>
  <% if can? :edit, :band %>
    <li class="nav-item"><%= link_to 'Combo aanpassen', edit_combo_path(@combo.id), class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Boeken', combos_booking_path, class: 'sub-nav-link' %></li>
<% end %>
<div class = "paddedcontainer-large">
  <h1>Combo aanpassen</h1>
  <%= bootstrap_form_for @combo do |a| %>
    <%= a.text_field :name, label: "Naam" %>
    <%= a.text_field :short_text, label: "Introductie zin" %>
    <%= a.text_area :description, label: "Beschrijving" %>
    <%= a.file_field :cover %>
    <%= a.file_field :tile %>
    <%= a.text_field :music_embed %>
    <%= a.text_field :facebook_uid %>
    <%= a.text_field :twitter_uid %>
    <%= a.submit 'Combo Aanpassen', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    ClassicEditor
        .create( document.querySelector( '#combo_description' ) )
        .catch( error => {
            console.error( error );
        }
    );
</script>

app/views/combos/index.html.erb
<% content_for :combomenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Nieuwe combo', new_combo_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Boeken', combos_booking_path, class: 'sub-nav-link' %></li>
<% end %>
<div class="jumbotron">
  <h1>Combo's</h1>
  <p>Groovercombo's zijn de officiele vereniging's bands van Groover. Deze bands kunnen worden
  ingehuurd voor feesten, evenementen, of andere aangelegenheden.</p>
  <a href="booking.html">Boeken</a>
</div>
<% if Combo.none? %>
  <h1>There are no combo's in the website database.</h1>
<% else %>
  <div class = "paddedcontainer-medium">
    <div class="row">
      <% @combo.each do |ccombo| %>
        <div class="col-sm-6 col-md-3">
          <div class="comboblock">
            <%= link_to(combo_path(ccombo.id)) do %>
            <div class="comboblockoverlay"></div>
            <%= image_tag ccombo.cover.url %>
            <div class="combotext">
              <h3><%= ccombo.name%></h3>
              <p><%= ccombo.short_text %></p>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/combos/new.html.erb
<% content_for :combomenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Nieuwe combo', new_combo_path, class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Boeken', '#', class: 'sub-nav-link' %></li>
<% end %>
<div class = "paddedcontainer-large">
  <h1>Nieuw Combo</h1>
  <%= bootstrap_form_for @combo do |a| %>
    <%= a.text_field :name, label: "Naam" %>
    <%= a.text_field :short_text, label: "Introductie zin" %>
    <%= a.text_area :description, label: "Beschrijving", control_class: "editor" %>
    <%= a.file_field :cover %>
    <%= a.text_field :music_embed %>
    <%= a.text_field :facebook_uid %>
    <%= a.text_field :twitter_uid %>
    <%= a.submit 'Nieuw combo aanmaken', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    var editor = ClassicEditor
        .create( document.querySelector( '#combo_description' ) )
        .catch( error => {
            console.error( error );
        }
    );
</script>

app/views/combos/show.html.erb
<% content_for :combomenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Nieuwe combo', new_combo_path, class: 'sub-nav-link' %></li>
  <% end %>
  <% if can? :edit, :band %>
    <li class="nav-item"><%= link_to 'Combo aanpassen', edit_combo_path(@combo.id), class: 'sub-nav-link' %></li>
  <% end %>
  <li class="nav-item"><%= link_to 'Boeken', combos_booking_path, class: 'sub-nav-link' %></li>
  <li class="nav-item"><%= link_to 'Terug naar overzicht', combos_path, class: 'sub-nav-link' %></li>
<% end %>
<div class="thumbnail">
  <% if @combo.tile.present? %>
    <%= image_tag @combo.tile.url %>
  <% else %>
    <%= image_tag @combo.cover.url %>
  <% end %>
  <h2 class = "withspacing"><%= @combo.name %></h2>
</div>
<div class = "paddedcontainer-medium">
  <div class="col-md-8">
    <p style="padding-left: 20px; padding-right: 20px;"><%= @combo.description.html_safe %></p>
  </div>
  <div class = "col-md-4">
    <% if @combo.music_embed.present? %>
      <div class="combosidebar">
        <%= @combo.music_embed.html_safe %>
        <script type="text/javascript">
        var iframeElement   = document.querySelector('iframe');
        var iframeElementID = iframeElement.id;
        var widget1         = SC.Widget(iframeElement);
        var widget2         = SC.Widget(iframeElementID);
        </script>
      </div>
    <% end %>
    <% if @combo.facebook_uid.present? %>
      <div class="combosidebar">
        <h3>Facebook</h3>
      </div>
    <% end %>
    <% if @combo.twitter_uid.present? %>
      <div class="combosidebar">
        <h3>Twitter</h3>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<% content_for :contactmenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Aanpassen', edit_contact_path, class: 'sub-nav-link' %></li>
  <% end %>
<% end %>

<div class = "paddedcontainer-large">
  <h1>Contactinformatie aanpassen</h1>
  <%= bootstrap_form_for @contact do |a| %>
    <%= a.text_area :bookingcontent %>
  	<%= a.text_area :content %>
    <%= a.submit 'Contactinformatie aanpassen', class: 'btn btn-primary' %>
  <% end %>
</div>
<script>
    ClassicEditor
        .create( document.querySelector( '#contact_content' ) )
        .catch( error => {
            console.error( error );
        } );
</script>
<script>
    ClassicEditor
        .create( document.querySelector( '#contact_bookingcontent' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

app/views/contacts/show.html.erb
<% content_for :contactmenu do %>
  <% if can? :new, :band %>
    <li class="nav-item"><%= link_to 'Aanpassen', edit_contact_path, class: 'sub-nav-link' %></li>
  <% end %>
<% end %>

<div class = "paddedcontainer-large">
	<h1>Contact</h1>
	<p><%= @contact.bookingcontent.html_safe %></p>
	<p><%= @contact.content.html_safe %></p>
</div>

app/views/dashboard/index.html.erb
<% content_for :groovermenu do %>
    <li class="nav-item"><%= link_to 'Uitloggen', destroy_user_session_path, method: 'delete', class: 'sub-nav-link' %></li>
<% end %>

app/views/home/index.html.erb
<div class="banner">
  <%= image_tag Association.first.banner.url %>
  <div class="title">
  	<div class="text">Delftse Studenten Jazz Vereniging</div>
  	<div class="groover">Groover</div>
  </div>
</div>