config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  get 'combos/booking', to: "combos#booking"
  resource :home, only: %i[ index ]
  resources :dashboard, only: %i[ index ]
  resources :articles, only: %i[ index show new create edit update ]
  resources :combos, only: %i[ index show new create edit update booking ]
  resource :contact, only: %i[ show edit update ]
  resource :association, only: %i[ show edit update ]

  # manually added links because the routing system is shit
  get 'association/commissions', to: "associations#commissions"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Anyone can see the index of news and individual articles
    can %i[ index show ], Article

    # Anyone can see the index of bands and individual band profiles
    can %i[ index show ], Combo
    can %i[ show ], Contact

    # Anyone can see the association information
    can %i[ show commissions ], Association

    if user.has_role? :admin
      # An administrator must be able to do anything in the system
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    dragonfly_accessor :cover

    validates_property :mime_type, of: :cover, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/association.rb
class Association < ApplicationRecord
	dragonfly_accessor :banner

	validates_property :mime_type, of: :banner, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/combo.rb
class Combo < ActiveRecord::Base
    dragonfly_accessor :cover
    dragonfly_accessor :tile

    validates_property :mime_type, of: :cover, in: %w(image/jpeg image/jpg image/png image/gif)
    validates_property :mime_type, of: :tile, in: %w(image/jpeg image/jpg image/png image/gif)
end

app/models/commission.rb
class Commission < ActiveRecord::Base
	
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def index
    @article = Article.all
    @association = Association.first
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'Het artikel is aangemaakt.'
      redirect_to articles_path
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'new'
    end
  end

  def edit; end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(article_params)
      flash[:success] = 'Het artikel is aangepast.'
      redirect_to article_path(@article)
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'edit'
    end
  end

  protected

  def article_params
    params.require(:article).permit(:title, :content, :cover)
  end
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  load_and_authorize_resource

  def index
    @combo = Combo.all
  end

  def show; end

  def new
    @combo = Combo.new
  end

  def create
    @combo = Combo.new(combo_params)

    if @combo.save
      flash[:success] = 'De combo is aangemaakt.'
      redirect_to combos_path
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'new'
    end
  end

  def edit; end

  def update
    @combo = Combo.find(params[:id])

    if @combo.update_attributes(combo_params)
      flash[:success] = 'Het combo is aangepast.'
      redirect_to combo_path(@combo)
    else
      flash[:danger] = 'Er is iets fout gegaan. Probeer het opnieuw.'
      render 'edit'
    end
  end

  def booking
    @combo = Combo.first
    @contact = Contact.first
  end

  protected

  def combo_params
    params.require(:combo).permit(:name, :description, :cover, :music_uid, :facebook_uid, :twitter_uid, :short_text)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  load_and_authorize_resource

  def show
  	@contact = Contact.first;
  end

  def edit
  	@contact = Contact.first;
  end

  def update
  	@contact = Contact.first;

  	if @contact.update_attributes(contact_params)
  		flash[:succes] = 'De contactinformatie is aangepast.'
  		redirect_to action: "show"
  	else
  		flash[:danger] = 'Er is iets fout gegaan gedurende het opslaan.'
  		render 'edit'
  	end
  end

  def contact_params
    params.require(:contact).permit(:content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
     { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
   end

   def flash_messages(opts = {})
     flash.each do |msg_type, message|
       concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
               concat message
             end)
     end
     nil
   end
end

app/helpers/association_helper.rb
module AssociationHelper
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groover</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-4 col-sm-3 col-md-2 col-lg-1 sidebar">
          <%= link_to image_tag('association/logo.png'), root_path %>
          <ul class="nav">
            <li class="nav-item"><%= link_to 'Nieuws', articles_path, class: 'nav-link' %></li>
            <% if content_for? :articlemenu %>
              <%= yield :articlemenu %>
            <% end %>
            <li class="nav-item"><%= link_to "Combo's", combos_path, class: 'nav-link' %></li>
            <% if content_for? :combomenu %>
              <%= yield :combomenu %>
            <% end %>
            <li class="nav-item"><%= link_to 'Vereniging', association_path, class: 'nav-link' %></li>
            <% if content_for? :associationmenu %>
              <%= yield :associationmenu %>
            <% end %>
            <li class="nav-item"><%= link_to 'Contact', contact_path, class: 'nav-link' %></li>
            <% if content_for? :contactmenu %>
              <%= yield :contactmenu %>
            <% end %>
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to 'Mijn Groover', dashboard_index_path, class: 'nav-link' %></li>
              <% if content_for? :groovermenu %>
                <%= yield :groovermenu %>
              <% end %>
            <% else %>
              <li class="nav-item"><%= link_to 'Mijn Groover', user_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>

        <div class="col-xs-8 col-sm-9 col-md-10 col-lg-11 mainbody pre-scrollable">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>